### ISSUE TITLE
Problem with imports while running tests

### ISSUE THREAD

**Issue by jnape** [andys8/create-react-app-purescript#1]
It appears as if the `App.test.tsx` file fails `craco test` with a fresh checkout and `yarn install`:

```log
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

    Check your code at App.tsx:23.
        in App (at App.test.tsx:6)
```

Seems like the purescript loader is not actually wired up correctly. Is there some missing step in the README to get this working?

**Comment by andys8** [comment]
Hey, I never looked into tests regarding this example. I'm also not sure if it's supposed to work. Depends on if `create-react-app` is using `webpack` at all or which config it's using. Or what `testing-library` is doing. Could also be using `jest` directly, I guess. But I don't know.

If you want to dig into it and come up with a solution, feel free to create a PR :)

**Comment by jnape** [comment]
Got it, just wanted to make sure I wasn't missing something intended by the walk through. Thanks for the quick reply!
